using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.Data.Sqlite;
using NewSchool.Models;

namespace NewSchool.Repositories
{
    /// <summary>
    /// WeeklyUnitPlan Repository
    /// 주차별 단원 배치 관리
    /// </summary>
    public class WeeklyUnitPlanRepository : BaseRepository
    {
        public WeeklyUnitPlanRepository(string dbPath) : base(dbPath)
        {
            EnsureTableExists();
        }

        #region Table Setup

        private void EnsureTableExists()
        {
            const string sql = @"
                CREATE TABLE IF NOT EXISTS WeeklyUnitPlan (
                    No INTEGER PRIMARY KEY AUTOINCREMENT,
                    YearPlanNo INTEGER NOT NULL,
                    Week INTEGER NOT NULL,
                    SectionNo INTEGER NOT NULL,
                    AllocatedHours INTEGER NOT NULL,
                    OrderInWeek INTEGER NOT NULL,
                    IsAutoGenerated INTEGER DEFAULT 1,
                    Status TEXT DEFAULT 'PLANNED',
                    FOREIGN KEY (YearPlanNo) REFERENCES SubjectYearPlan(No) ON DELETE CASCADE,
                    FOREIGN KEY (SectionNo) REFERENCES CourseSection(No) ON DELETE CASCADE
                );

                CREATE INDEX IF NOT EXISTS idx_unit_plan_week
                    ON WeeklyUnitPlan(YearPlanNo, Week);
                CREATE INDEX IF NOT EXISTS idx_unit_plan_section
                    ON WeeklyUnitPlan(YearPlanNo, SectionNo);
            ";

            using var cmd = Connection.CreateCommand();
            cmd.CommandText = sql;
            cmd.ExecuteNonQuery();

            // 기존 테이블에 UnitNo가 있으면 SectionNo로 변경 (마이그레이션)
            MigrateUnitNoToSectionNo();

            LogInfo("WeeklyUnitPlan 테이블 확인/생성 완료");
        }

        private void MigrateUnitNoToSectionNo()
        {
            try
            {
                // 컬럼 존재 여부 확인
                const string checkColumn = "SELECT EXISTS(SELECT 1 FROM pragma_table_info('WeeklyUnitPlan') WHERE name = 'UnitNo')";
                using var checkCmd = Connection.CreateCommand();
                checkCmd.CommandText = checkColumn;
                var hasUnitNo = Convert.ToInt32(checkCmd.ExecuteScalar()) == 1;

                if (hasUnitNo)
                {
                    // UnitNo 컬럼이 있으면 SectionNo로 데이터 복사 후 테이블 재생성
                    // SQLite는 ALTER COLUMN을 지원하지 않으므로 테이블 재생성 필요
                    const string migrate = @"
                        -- 임시 테이블 생성
                        CREATE TABLE IF NOT EXISTS WeeklyUnitPlan_new (
                            No INTEGER PRIMARY KEY AUTOINCREMENT,
                            YearPlanNo INTEGER NOT NULL,
                            Week INTEGER NOT NULL,
                            SectionNo INTEGER NOT NULL,
                            AllocatedHours INTEGER NOT NULL,
                            OrderInWeek INTEGER NOT NULL,
                            IsAutoGenerated INTEGER DEFAULT 1,
                            Status TEXT DEFAULT 'PLANNED'
                        );

                        -- 데이터 복사
                        INSERT OR IGNORE INTO WeeklyUnitPlan_new (No, YearPlanNo, Week, SectionNo, AllocatedHours, OrderInWeek, IsAutoGenerated, Status)
                        SELECT No, YearPlanNo, Week, UnitNo, AllocatedHours, OrderInWeek, IsAutoGenerated, Status
                        FROM WeeklyUnitPlan;

                        -- 기존 테이블 삭제
                        DROP TABLE WeeklyUnitPlan;

                        -- 새 테이블로 이름 변경
                        ALTER TABLE WeeklyUnitPlan_new RENAME TO WeeklyUnitPlan;
                    ";

                    using var migrateCmd = Connection.CreateCommand();
                    migrateCmd.CommandText = migrate;
                    migrateCmd.ExecuteNonQuery();

                    LogInfo("WeeklyUnitPlan: UnitNo → SectionNo 마이그레이션 완료");
                }
            }
            catch (Exception ex)
            {
                LogError($"WeeklyUnitPlan 마이그레이션 실패: {ex.Message}", ex);
            }
        }

        #endregion

        #region Create

        /// <summary>
        /// 단원 배치 생성
        /// </summary>
        public async Task<int> CreateAsync(WeeklyUnitPlan plan)
        {
            const string query = @"
                INSERT INTO WeeklyUnitPlan (
                    YearPlanNo, Week, SectionNo, AllocatedHours,
                    OrderInWeek, IsAutoGenerated, Status
                ) VALUES (
                    @YearPlanNo, @Week, @SectionNo, @AllocatedHours,
                    @OrderInWeek, @IsAutoGenerated, @Status
                );
                SELECT last_insert_rowid();";

            try
            {
                using var cmd = CreateCommand(query);
                AddParameters(cmd, plan);

                var result = await cmd.ExecuteScalarAsync();
                plan.No = Convert.ToInt32(result);

                LogInfo($"단원 배치 생성 완료: No={plan.No}, Week={plan.Week}, SectionNo={plan.SectionNo}");
                return plan.No;
            }
            catch (Exception ex)
            {
                LogError($"단원 배치 생성 실패: Week={plan.Week}, SectionNo={plan.SectionNo}", ex);
                throw;
            }
        }

        /// <summary>
        /// 단원 배치 일괄 생성
        /// </summary>
        public async Task<int> CreateBatchAsync(List<WeeklyUnitPlan> plans)
        {
            if (plans == null || plans.Count == 0)
                return 0;

            int count = 0;

            try
            {
                BeginTransaction();

                foreach (var plan in plans)
                {
                    await CreateAsync(plan);
                    count++;
                }

                Commit();
                LogInfo($"단원 배치 일괄 생성 완료: {count}개");
                return count;
            }
            catch (Exception ex)
            {
                Rollback();
                LogError($"단원 배치 일괄 생성 실패", ex);
                throw;
            }
        }

        #endregion

        #region Read

        /// <summary>
        /// No로 조회
        /// </summary>
        public async Task<WeeklyUnitPlan?> GetByIdAsync(int no)
        {
            const string query = "SELECT * FROM WeeklyUnitPlan WHERE No = @No";

            try
            {
                using var cmd = CreateCommand(query);
                cmd.Parameters.AddWithValue("@No", no);

                using var reader = await cmd.ExecuteReaderAsync();
                if (await reader.ReadAsync())
                {
                    return MapPlan(reader);
                }
                return null;
            }
            catch (Exception ex)
            {
                LogError($"단원 배치 조회 실패: No={no}", ex);
                throw;
            }
        }

        /// <summary>
        /// 연간계획별 전체 배치 조회
        /// </summary>
        public async Task<List<WeeklyUnitPlan>> GetByYearPlanAsync(int yearPlanNo)
        {
            const string query = @"
                SELECT * FROM WeeklyUnitPlan
                WHERE YearPlanNo = @YearPlanNo
                ORDER BY Week, OrderInWeek";

            try
            {
                using var cmd = CreateCommand(query);
                cmd.Parameters.AddWithValue("@YearPlanNo", yearPlanNo);

                var plans = new List<WeeklyUnitPlan>();
                using var reader = await cmd.ExecuteReaderAsync();
                while (await reader.ReadAsync())
                {
                    plans.Add(MapPlan(reader));
                }
                return plans;
            }
            catch (Exception ex)
            {
                LogError($"연간계획별 단원 배치 조회 실패: YearPlanNo={yearPlanNo}", ex);
                throw;
            }
        }

        /// <summary>
        /// 특정 주차의 배치 조회
        /// </summary>
        public async Task<List<WeeklyUnitPlan>> GetByWeekAsync(int yearPlanNo, int week)
        {
            const string query = @"
                SELECT * FROM WeeklyUnitPlan
                WHERE YearPlanNo = @YearPlanNo AND Week = @Week
                ORDER BY OrderInWeek";

            try
            {
                using var cmd = CreateCommand(query);
                cmd.Parameters.AddWithValue("@YearPlanNo", yearPlanNo);
                cmd.Parameters.AddWithValue("@Week", week);

                var plans = new List<WeeklyUnitPlan>();
                using var reader = await cmd.ExecuteReaderAsync();
                while (await reader.ReadAsync())
                {
                    plans.Add(MapPlan(reader));
                }
                return plans;
            }
            catch (Exception ex)
            {
                LogError($"주차별 단원 배치 조회 실패: Week={week}", ex);
                throw;
            }
        }

        /// <summary>
        /// 특정 단원(Section)의 배치 조회
        /// </summary>
        public async Task<List<WeeklyUnitPlan>> GetBySectionAsync(int yearPlanNo, int sectionNo)
        {
            const string query = @"
                SELECT * FROM WeeklyUnitPlan
                WHERE YearPlanNo = @YearPlanNo AND SectionNo = @SectionNo
                ORDER BY Week";

            try
            {
                using var cmd = CreateCommand(query);
                cmd.Parameters.AddWithValue("@YearPlanNo", yearPlanNo);
                cmd.Parameters.AddWithValue("@SectionNo", sectionNo);

                var plans = new List<WeeklyUnitPlan>();
                using var reader = await cmd.ExecuteReaderAsync();
                while (await reader.ReadAsync())
                {
                    plans.Add(MapPlan(reader));
                }
                return plans;
            }
            catch (Exception ex)
            {
                LogError($"단원별 배치 조회 실패: SectionNo={sectionNo}", ex);
                throw;
            }
        }

        /// <summary>
        /// 수동 배치만 조회
        /// </summary>
        public async Task<List<WeeklyUnitPlan>> GetManualPlansAsync(int yearPlanNo)
        {
            const string query = @"
                SELECT * FROM WeeklyUnitPlan
                WHERE YearPlanNo = @YearPlanNo AND IsAutoGenerated = 0
                ORDER BY Week, OrderInWeek";

            try
            {
                using var cmd = CreateCommand(query);
                cmd.Parameters.AddWithValue("@YearPlanNo", yearPlanNo);

                var plans = new List<WeeklyUnitPlan>();
                using var reader = await cmd.ExecuteReaderAsync();
                while (await reader.ReadAsync())
                {
                    plans.Add(MapPlan(reader));
                }
                return plans;
            }
            catch (Exception ex)
            {
                LogError($"수동 배치 조회 실패: YearPlanNo={yearPlanNo}", ex);
                throw;
            }
        }

        /// <summary>
        /// 상태별 배치 조회
        /// </summary>
        public async Task<List<WeeklyUnitPlan>> GetByStatusAsync(int yearPlanNo, string status)
        {
            const string query = @"
                SELECT * FROM WeeklyUnitPlan
                WHERE YearPlanNo = @YearPlanNo AND Status = @Status
                ORDER BY Week, OrderInWeek";

            try
            {
                using var cmd = CreateCommand(query);
                cmd.Parameters.AddWithValue("@YearPlanNo", yearPlanNo);
                cmd.Parameters.AddWithValue("@Status", status);

                var plans = new List<WeeklyUnitPlan>();
                using var reader = await cmd.ExecuteReaderAsync();
                while (await reader.ReadAsync())
                {
                    plans.Add(MapPlan(reader));
                }
                return plans;
            }
            catch (Exception ex)
            {
                LogError($"상태별 배치 조회 실패: Status={status}", ex);
                throw;
            }
        }

        /// <summary>
        /// 특정 주의 다음 OrderInWeek 값 조회
        /// </summary>
        public async Task<int> GetNextOrderInWeekAsync(int yearPlanNo, int week)
        {
            const string query = @"
                SELECT COALESCE(MAX(OrderInWeek), 0) + 1
                FROM WeeklyUnitPlan
                WHERE YearPlanNo = @YearPlanNo AND Week = @Week";

            try
            {
                using var cmd = CreateCommand(query);
                cmd.Parameters.AddWithValue("@YearPlanNo", yearPlanNo);
                cmd.Parameters.AddWithValue("@Week", week);

                var result = await cmd.ExecuteScalarAsync();
                return Convert.ToInt32(result);
            }
            catch (Exception ex)
            {
                LogError($"다음 순서 조회 실패: Week={week}", ex);
                throw;
            }
        }

        /// <summary>
        /// 특정 주의 총 할당 시수
        /// </summary>
        public async Task<int> GetTotalAllocatedHoursAsync(int yearPlanNo, int week)
        {
            const string query = @"
                SELECT COALESCE(SUM(AllocatedHours), 0)
                FROM WeeklyUnitPlan
                WHERE YearPlanNo = @YearPlanNo AND Week = @Week";

            try
            {
                using var cmd = CreateCommand(query);
                cmd.Parameters.AddWithValue("@YearPlanNo", yearPlanNo);
                cmd.Parameters.AddWithValue("@Week", week);

                var result = await cmd.ExecuteScalarAsync();
                return Convert.ToInt32(result);
            }
            catch (Exception ex)
            {
                LogError($"총 할당 시수 조회 실패: Week={week}", ex);
                throw;
            }
        }

        #endregion

        #region Update

        /// <summary>
        /// 단원 배치 수정
        /// </summary>
        public async Task<bool> UpdateAsync(WeeklyUnitPlan plan)
        {
            const string query = @"
                UPDATE WeeklyUnitPlan SET
                    YearPlanNo = @YearPlanNo,
                    Week = @Week,
                    SectionNo = @SectionNo,
                    AllocatedHours = @AllocatedHours,
                    OrderInWeek = @OrderInWeek,
                    IsAutoGenerated = @IsAutoGenerated,
                    Status = @Status
                WHERE No = @No";

            try
            {
                using var cmd = CreateCommand(query);
                AddParameters(cmd, plan);

                int affected = await cmd.ExecuteNonQueryAsync();
                bool success = affected > 0;

                if (success)
                    LogInfo($"단원 배치 수정 완료: No={plan.No}");

                return success;
            }
            catch (Exception ex)
            {
                LogError($"단원 배치 수정 실패: No={plan.No}", ex);
                throw;
            }
        }

        /// <summary>
        /// 상태 변경
        /// </summary>
        public async Task<bool> UpdateStatusAsync(int no, string status)
        {
            const string query = @"
                UPDATE WeeklyUnitPlan SET Status = @Status
                WHERE No = @No";

            try
            {
                using var cmd = CreateCommand(query);
                cmd.Parameters.AddWithValue("@No", no);
                cmd.Parameters.AddWithValue("@Status", status);

                int affected = await cmd.ExecuteNonQueryAsync();
                return affected > 0;
            }
            catch (Exception ex)
            {
                LogError($"상태 변경 실패: No={no}", ex);
                throw;
            }
        }

        /// <summary>
        /// 할당 시수 수정
        /// </summary>
        public async Task<bool> UpdateAllocatedHoursAsync(int no, int allocatedHours)
        {
            const string query = @"
                UPDATE WeeklyUnitPlan SET AllocatedHours = @AllocatedHours
                WHERE No = @No";

            try
            {
                using var cmd = CreateCommand(query);
                cmd.Parameters.AddWithValue("@No", no);
                cmd.Parameters.AddWithValue("@AllocatedHours", allocatedHours);

                int affected = await cmd.ExecuteNonQueryAsync();
                return affected > 0;
            }
            catch (Exception ex)
            {
                LogError($"할당 시수 수정 실패: No={no}", ex);
                throw;
            }
        }

        /// <summary>
        /// 수동 배치로 변경
        /// </summary>
        public async Task<bool> SetManualAsync(int no)
        {
            const string query = @"
                UPDATE WeeklyUnitPlan SET IsAutoGenerated = 0
                WHERE No = @No";

            try
            {
                using var cmd = CreateCommand(query);
                cmd.Parameters.AddWithValue("@No", no);

                int affected = await cmd.ExecuteNonQueryAsync();
                return affected > 0;
            }
            catch (Exception ex)
            {
                LogError($"수동 배치 변경 실패: No={no}", ex);
                throw;
            }
        }

        #endregion

        #region Delete

        /// <summary>
        /// 삭제
        /// </summary>
        public async Task<bool> DeleteAsync(int no)
        {
            const string query = "DELETE FROM WeeklyUnitPlan WHERE No = @No";

            try
            {
                using var cmd = CreateCommand(query);
                cmd.Parameters.AddWithValue("@No", no);

                int affected = await cmd.ExecuteNonQueryAsync();
                bool success = affected > 0;

                if (success)
                    LogInfo($"단원 배치 삭제 완료: No={no}");

                return success;
            }
            catch (Exception ex)
            {
                LogError($"단원 배치 삭제 실패: No={no}", ex);
                throw;
            }
        }

        /// <summary>
        /// 연간계획별 전체 삭제
        /// </summary>
        public async Task<int> DeleteByYearPlanAsync(int yearPlanNo)
        {
            const string query = "DELETE FROM WeeklyUnitPlan WHERE YearPlanNo = @YearPlanNo";

            try
            {
                using var cmd = CreateCommand(query);
                cmd.Parameters.AddWithValue("@YearPlanNo", yearPlanNo);

                int affected = await cmd.ExecuteNonQueryAsync();
                LogInfo($"연간계획별 단원 배치 삭제 완료: YearPlanNo={yearPlanNo}, 삭제 수={affected}");
                return affected;
            }
            catch (Exception ex)
            {
                LogError($"연간계획별 단원 배치 삭제 실패: YearPlanNo={yearPlanNo}", ex);
                throw;
            }
        }

        /// <summary>
        /// 자동 배치만 삭제 (수동 배치 유지)
        /// </summary>
        public async Task<int> DeleteAutoGeneratedAsync(int yearPlanNo)
        {
            const string query = @"
                DELETE FROM WeeklyUnitPlan
                WHERE YearPlanNo = @YearPlanNo AND IsAutoGenerated = 1";

            try
            {
                using var cmd = CreateCommand(query);
                cmd.Parameters.AddWithValue("@YearPlanNo", yearPlanNo);

                int affected = await cmd.ExecuteNonQueryAsync();
                LogInfo($"자동 배치 삭제 완료: YearPlanNo={yearPlanNo}, 삭제 수={affected}");
                return affected;
            }
            catch (Exception ex)
            {
                LogError($"자동 배치 삭제 실패: YearPlanNo={yearPlanNo}", ex);
                throw;
            }
        }

        /// <summary>
        /// 특정 주차 이후 자동 배치 삭제
        /// </summary>
        public async Task<int> DeleteAutoGeneratedFromWeekAsync(int yearPlanNo, int fromWeek)
        {
            const string query = @"
                DELETE FROM WeeklyUnitPlan
                WHERE YearPlanNo = @YearPlanNo
                  AND Week >= @FromWeek
                  AND IsAutoGenerated = 1";

            try
            {
                using var cmd = CreateCommand(query);
                cmd.Parameters.AddWithValue("@YearPlanNo", yearPlanNo);
                cmd.Parameters.AddWithValue("@FromWeek", fromWeek);

                int affected = await cmd.ExecuteNonQueryAsync();
                LogInfo($"특정 주차 이후 자동 배치 삭제: YearPlanNo={yearPlanNo}, FromWeek={fromWeek}, 삭제 수={affected}");
                return affected;
            }
            catch (Exception ex)
            {
                LogError($"특정 주차 이후 자동 배치 삭제 실패: YearPlanNo={yearPlanNo}", ex);
                throw;
            }
        }

        #endregion

        #region Helper Methods

        private void AddParameters(SqliteCommand cmd, WeeklyUnitPlan plan)
        {
            cmd.Parameters.AddWithValue("@No", plan.No);
            cmd.Parameters.AddWithValue("@YearPlanNo", plan.YearPlanNo);
            cmd.Parameters.AddWithValue("@Week", plan.Week);
            cmd.Parameters.AddWithValue("@SectionNo", plan.SectionNo);
            cmd.Parameters.AddWithValue("@AllocatedHours", plan.AllocatedHours);
            cmd.Parameters.AddWithValue("@OrderInWeek", plan.OrderInWeek);
            cmd.Parameters.AddWithValue("@IsAutoGenerated", plan.IsAutoGenerated);
            cmd.Parameters.AddWithValue("@Status", plan.Status ?? "PLANNED");
        }

        private WeeklyUnitPlan MapPlan(SqliteDataReader reader)
        {
            return new WeeklyUnitPlan
            {
                No = reader.GetInt32(reader.GetOrdinal("No")),
                YearPlanNo = reader.GetInt32(reader.GetOrdinal("YearPlanNo")),
                Week = reader.GetInt32(reader.GetOrdinal("Week")),
                SectionNo = reader.GetInt32(reader.GetOrdinal("SectionNo")),
                AllocatedHours = reader.GetInt32(reader.GetOrdinal("AllocatedHours")),
                OrderInWeek = reader.GetInt32(reader.GetOrdinal("OrderInWeek")),
                IsAutoGenerated = reader.GetInt32(reader.GetOrdinal("IsAutoGenerated")),
                Status = reader.GetString(reader.GetOrdinal("Status"))
            };
        }

        #endregion
    }
}
