namespace NewSchool.Models
{
    /// <summary>
    /// 주차별 단원 배치
    /// 어느 주에 어떤 단원을 몇 시간 진행할지 기록
    /// </summary>
    public class WeeklyUnitPlan : NotifyPropertyChangedBase, IEntity
    {
        #region Fields

        private int _no = -1;
        private int _yearPlanNo;
        private int _week;
        private int _sectionNo;
        private int _allocatedHours;
        private int _orderInWeek;
        private int _isAutoGenerated = 1;
        private string _status = "PLANNED";

        #endregion

        #region Properties - 기본 정보

        /// <summary>PK (자동 증가)</summary>
        public int No
        {
            get => _no;
            set => SetProperty(ref _no, value);
        }

        /// <summary>연간계획 FK (SubjectYearPlan.No)</summary>
        public int YearPlanNo
        {
            get => _yearPlanNo;
            set => SetProperty(ref _yearPlanNo, value);
        }

        #endregion

        #region Properties - 배치 정보

        /// <summary>주차</summary>
        public int Week
        {
            get => _week;
            set => SetProperty(ref _week, value);
        }

        /// <summary>단원 FK (CourseSection.No)</summary>
        public int SectionNo
        {
            get => _sectionNo;
            set => SetProperty(ref _sectionNo, value);
        }

        /// <summary>해당 주에 이 단원에 할당된 시수</summary>
        public int AllocatedHours
        {
            get => _allocatedHours;
            set => SetProperty(ref _allocatedHours, value);
        }

        /// <summary>같은 주에 여러 단원 있을 경우 순서</summary>
        public int OrderInWeek
        {
            get => _orderInWeek;
            set => SetProperty(ref _orderInWeek, value);
        }

        #endregion

        #region Properties - 생성/상태

        /// <summary>자동 생성 여부 (0=수동, 1=자동)</summary>
        public int IsAutoGenerated
        {
            get => _isAutoGenerated;
            set => SetProperty(ref _isAutoGenerated, value);
        }

        /// <summary>상태: PLANNED, IN_PROGRESS, COMPLETED</summary>
        public string Status
        {
            get => _status;
            set => SetProperty(ref _status, value);
        }

        #endregion

        #region Navigation Properties

        /// <summary>단원 정보 (ViewModel에서 설정)</summary>
        public CourseSection? Section { get; set; }

        #endregion

        #region Computed Properties

        /// <summary>수동 배치 여부</summary>
        public bool IsManuallyPlaced => IsAutoGenerated == 0;

        /// <summary>자동 배치 여부</summary>
        public bool IsAutomaticallyPlaced => IsAutoGenerated == 1;

        /// <summary>주차 표시</summary>
        public string WeekDisplay => $"{Week}주차";

        /// <summary>상태 표시</summary>
        public string StatusDisplay => Status switch
        {
            "PLANNED" => "계획됨",
            "IN_PROGRESS" => "진행중",
            "COMPLETED" => "완료",
            _ => Status
        };

        /// <summary>진행중 여부</summary>
        public bool IsInProgress => Status == "IN_PROGRESS";

        /// <summary>완료 여부</summary>
        public bool IsCompleted => Status == "COMPLETED";

        /// <summary>단원명 (Section이 설정된 경우)</summary>
        public string UnitName => Section?.SectionName ?? $"단원 #{SectionNo}";

        #endregion

        #region Methods

        public override string ToString()
        {
            return $"{WeekDisplay} - {UnitName} ({AllocatedHours}시간)";
        }

        #endregion
    }
}
